# Generated by Django 5.2.8 on 2025-11-08 09:40

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.PositiveIntegerField(default=orders.models.generate_order_id, primary_key=True, serialize=False, verbose_name='Buyurtma ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ism-familya')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('direction', models.CharField(blank=True, choices=[('kiruvchi', 'Kiruvchi'), ('chiquvchi', 'Chiquvchi')], max_length=10, null=True, verbose_name="Yo'nalish")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('status', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('bajarildi', 'Bajarildi'), ('bekor_qilindi', 'Bekor qilindi')], default='kutilmoqda', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'kuryer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Tayinlangan kuryer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
