# Generated by Django 5.2.8 on 2025-11-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ism-familya')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('location_name', models.CharField(max_length=255, verbose_name='Manzil nomi/Tavsifi')),
                ('address', models.TextField(verbose_name="To'liq manzil")),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Mijoz haqida izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Buyurtma ID')),
                ('kiruvchi_soni', models.PositiveIntegerField(default=0, verbose_name='Kiruvchi buyumlar soni')),
                ('chiquvchi_soni', models.PositiveIntegerField(default=0, verbose_name='Chiquvchi buyumlar soni')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Buyurtma haqida izoh')),
                ('status', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('bajarildi', 'Bajarildi'), ('bekor_qilindi', 'Bekor qilindi')], default='kutilmoqda', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
