# Generated by Django 5.2.8 on 2025-11-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='direction',
        ),
        migrations.AddField(
            model_name='order',
            name='chiquvchi_soni',
            field=models.PositiveIntegerField(default=0, verbose_name='Chiquvchi buyumlar soni'),
        ),
        migrations.AddField(
            model_name='order',
            name='kiruvchi_soni',
            field=models.PositiveIntegerField(default=0, verbose_name='Kiruvchi buyumlar soni'),
        ),
    ]
