# Generated by Django 5.2.8 on 2025-11-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='chiquvchi_soni',
        ),
        migrations.RemoveField(
            model_name='order',
            name='kiruvchi_soni',
        ),
        migrations.AddField(
            model_name='order',
            name='baklashka_soni',
            field=models.PositiveIntegerField(default=0, verbose_name='Baklashkalar soni'),
        ),
        migrations.AddField(
            model_name='order',
            name='kuler_soni',
            field=models.PositiveIntegerField(default=0, verbose_name='Kulerlar soni'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('kútilmekte', 'kútilmekte'), ('orınlandı', 'orınlandı'), ('bekor_qilindi', 'Bekor qilindi')], default='kútilmekte', max_length=15, verbose_name='Status'),
        ),
    ]
