# Generated by Django 5.2.8 on 2025-11-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_chiquvchi_soni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='location_name',
        ),
    ]
