# Generated by Django 5.2.8 on 2025-11-11 17:47

from django.db import migrations
from django.utils import timezone


def fix_null_created_at(apps, schema_editor):
    """
    Fix orders with NULL created_at by setting them to current date
    """
    Order = apps.get_model('orders', 'Order')
    # Update orders with NULL created_at to current date
    Order.objects.filter(created_at__isnull=True).update(created_at=timezone.now().date())


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_price_and_datefield'),
    ]

    operations = [
        migrations.RunPython(fix_null_created_at),
    ]
