# Generated by Django 5.2.8 on 2025-11-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_fix_null_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pompa_soni',
            field=models.PositiveIntegerField(default=0, verbose_name='Pompalar soni'),
        ),
    ]
