# Generated by Django 5.2.8 on 2025-11-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_pompa_soni'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arenda_soni',
            field=models.PositiveIntegerField(default=0, verbose_name='Arenda soni'),
        ),
        migrations.AddField(
            model_name='order',
            name='baklashkasiz_soni',
            field=models.PositiveIntegerField(default=0, verbose_name='Baklashkasiz soni'),
        ),
    ]
