# Generated by Django 5.2.8 on 2025-12-14 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_arenda_baklashkasiz_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_debit',
            field=models.BooleanField(default=False, verbose_name='Qarz'),
        ),
        migrations.CreateModel(
            name='ClientNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baklashka_soni', models.PositiveIntegerField(default=0, verbose_name='Baklashkalar soni')),
                ('arenda_soni', models.PositiveIntegerField(default=0, verbose_name='Arenda soni')),
                ('kuler_soni', models.PositiveIntegerField(default=0, verbose_name='Kulerlar soni')),
                ('pompa_soni', models.PositiveIntegerField(default=0, verbose_name='Pompalar soni')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='orders.client')),
            ],
            options={
                'verbose_name': 'Client Notes',
                'verbose_name_plural': 'Client Notes',
            },
        ),
    ]
