# Generated by Django 5.2.8 on 2026-02-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_is_debit_clientnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('kuryerga_berildi', 'Kuryerga berildi'), ('yolda', "Yo'lda"), ('yetkazildi', 'Yetkazildi'), ('bajarildi', 'Bajarildi'), ('bekor_qilindi', 'Bekor qilindi')], default='kutilmoqda', max_length=20, verbose_name='Status'),
        ),
    ]
